name = "pixellab45-v2"
main = "index.js"
compatibility_date = "2026-06-11"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "pixellab45-images"

[[r2_buckets]]
binding = "EBOOKS"
bucket_name = "pixellab45-ebooks"

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
