name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #=========================================
      # GENERAR VERSIÓN AUTOMÁTICA
      #=========================================
      - name: Inject version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)

          find . -type f \( -name "*.html" -o -name "*.js" \) \
            -exec sed -i "s/__VERSION__/${VERSION}/g" {} \;
      - name: Inject version
        run: |
         VERSION=$(date +%Y%m%d%H%M%S)
            echo "VERSION=$VERSION"

              find . -type f \( -name "*.html" -o -name "*.js" \) \
         -exec sed -i "s/__VERSION__/${VERSION}/g" {} \;

                   echo "=== index.html ==="
                               grep "__VERSION__" index.html || true
          grep "script.js?v=" index.html || true
          grep "Versión:" index.html
      #=========================================
      # VERIFICAR REEMPLAZO
      #=========================================
      - name: Verificar VERSION
        run: |
          echo "Buscando __VERSION__..."
          grep -R "__VERSION__" . || true

          echo "Buscando referencias a script.js..."
          grep -R "script.js?v=" . || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
